services:
  app:
    build: .
    ports:
      - "127.0.0.1:3030:3030"
    environment:
      DATABASE_URL: "postgresql://postgres:123456@db:5432/hits"
    command: >
      sh -c "
      sqlx database create &&
      sqlx migrate run &&
      ./hits
      "
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: hits
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
